<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2DAF030" failures="2" tests="13" name="Test" time="0.188" errors="0" timestamp="10 Feb 2022 16:50:59 GMT">
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="check2" time="0.027">
    <skipped/>
  </testcase> <!-- check2 -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="check2" time="0.007">
    <skipped/>
  </testcase> <!-- check2 -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="check2" time="0.003">
    <skipped/>
  </testcase> <!-- check2 -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="check2" time="0.004">
    <skipped/>
  </testcase> <!-- check2 -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="check2" time="0.003">
    <skipped/>
  </testcase> <!-- check2 -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="check2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [321] but found [123]">
      <![CDATA[java.lang.AssertionError: expected [321] but found [123]
at com.AllTestNG_Functions.Retry1_Class.check2(Retry1_Class.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- check2 -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="checkPassword" time="0.003"/>
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="checkUserName" time="0.007">
    <skipped/>
  </testcase> <!-- checkUserName -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="checkUserName" time="0.002">
    <skipped/>
  </testcase> <!-- checkUserName -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="checkUserName" time="0.003">
    <skipped/>
  </testcase> <!-- checkUserName -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="checkUserName" time="0.002">
    <skipped/>
  </testcase> <!-- checkUserName -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="checkUserName" time="0.002">
    <skipped/>
  </testcase> <!-- checkUserName -->
  <testcase classname="com.AllTestNG_Functions.Retry1_Class" name="checkUserName" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [vel] but found [Raja]">
      <![CDATA[java.lang.AssertionError: expected [vel] but found [Raja]
at com.AllTestNG_Functions.Retry1_Class.checkUserName(Retry1_Class.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkUserName -->
</testsuite> <!-- Test -->
